name: Java CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      TRACK_MY_CASE_URL: ${{ secrets.TRACK_MY_CASE_URL }}
      ONE_LOGIN_EMAIL: ${{ secrets.ONE_LOGIN_EMAIL }}
      ONE_LOGIN_PASSWORD: ${{ secrets.ONE_LOGIN_PASSWORD }}
      ONE_LOGIN_2FA: ${{ secrets.ONE_LOGIN_2FA }}
      AMP_BACKEND_URL: ${{ secrets.AMP_BACKEND_URL }}
      CP_BACKEND_URL: ${{ secrets.CP_BACKEND_URL }}
      CJSCPPUID: ${{ secrets.CJSCPPUID }}
      APIM_CP_BACKEND_URL: ${{ secrets.APIM_CP_BACKEND_URL }}
      APIM_SUBSCRIPTION_KEY: ${{ secrets.APIM_SUBSCRIPTION_KEY }}
    strategy:
      matrix:
        task: [ check, test ]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Run Gradle ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}
